install.packages("xtable", repos="http://cran.us.r-project.org")
install.packages("openxlsx", repos="http://cran.us.r-project.org")
install.packages("readxl", repos="http://cran.us.r-project.org")
install.packages("cluster", repos="http://cran.us.r-project.org")
print('The End of the R Libraries Installation Script. (maybe unsuccessful')
