install.packages("xtable", repos="http://cran.us.r-project.org")
install.packages("openxlsx", repos="http://cran.us.r-project.org")
install.packages("readxl", repos="http://cran.us.r-project.org")
install.packages("clusteval", repos="http://cran.us.r-project.org")
install.packages("vegan", repos="http://cran.us.r-project.org")
print('The End 777 of the R Libraries Installation Script. (maybe unsuccessful)')
