# Generated by Django 3.0.10 on 2021-02-08 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20210209_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('o', 'On loan')], default='m', help_text='Book availability', max_length=1),
        ),
    ]
