# Generated by Django 3.0.10 on 2021-02-09 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20210209_0236'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='ФИО')),
                ('name_space', models.CharField(max_length=120, verbose_name='Локация')),
                ('organization', models.CharField(blank=True, max_length=120, null=True, verbose_name='Организация')),
                ('position', models.CharField(blank=True, max_length=120, null=True, verbose_name='Должность')),
                ('email', models.EmailField(blank=True, max_length=120, null=True, verbose_name='Email')),
                ('description', models.CharField(blank=True, max_length=120, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Запрос на доступ к базе данных',
                'verbose_name_plural': 'Запросы на доступ к базам данных',
            },
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('o', 'Available')], default='m', help_text='Book availability', max_length=1),
        ),
    ]
