# Generated by Django 3.0.10 on 2021-02-09 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20210210_0217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name_plural': 'Requests to access the datasets'},
        ),
    ]
