# Generated by Django 3.0.10 on 2021-02-10 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_feedback_borrower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='borrower',
        ),
        migrations.AddField(
            model_name='feedback',
            name='customer_login',
            field=models.CharField(max_length=120, null=True, verbose_name='Логин заказчика'),
        ),
    ]
