# Generated by Django 3.0.10 on 2021-02-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20210210_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(blank=True, choices=[('o', 'Available'), ('m', 'Refusal'), ('d', 'Waiting')], default='d', help_text='Доступ датасета', max_length=1),
        ),
    ]
