# Generated by Django 3.0.10 on 2021-03-05 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20210303_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='customer_login',
            field=models.CharField(max_length=120, null=True, verbose_name='Login user'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='description',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(blank=True, max_length=120, null=True, verbose_name='eMail'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Surname'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name_space',
            field=models.CharField(max_length=120, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='organization',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='position',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(blank=True, choices=[('o', 'Available'), ('m', 'Refusal'), ('d', 'Waiting')], default='d', help_text='STATUS', max_length=1),
        ),
    ]
