# Generated by Django 3.0.10 on 2021-03-05 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20210306_0136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinstance',
            name='due_back',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='imprint',
        ),
    ]
