# Generated by Django 3.0.10 on 2021-03-05 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_auto_20210306_0211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['book']},
        ),
        migrations.RemoveField(
            model_name='author',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='author',
            name='date_of_death',
        ),
    ]
