# Generated by Django 3.0.10 on 2021-03-06 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_auto_20210306_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='customer_login',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Login user'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(blank=True, max_length=120, null=True, verbose_name='eMail'),
        ),
    ]
