# Generated by Django 3.0.10 on 2021-03-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='birth date'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='phone number'),
        ),
    ]
