# Generated by Django 3.0.10 on 2021-03-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_auto_20210307_0327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Dataset'},
        ),
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['book'], 'verbose_name': 'Dataset instance'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Requests to access the dataset'},
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(blank=True, default='None', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(blank=True, choices=[('o', 'Available'), ('m', 'Refused'), ('d', 'Waiting')], default='d', help_text='STATUS', max_length=1),
        ),
    ]
