# Generated by Django 3.0.10 on 2021-04-01 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_auto_20210315_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='first_name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='first_name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='last_name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='last_name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='summary_en',
            field=models.TextField(blank=True, help_text='Enter a brief description of the book', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='summary_ru',
            field=models.TextField(blank=True, help_text='Enter a brief description of the book', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='status_en',
            field=models.CharField(blank=True, choices=[('o', 'Available'), ('m', 'Refused'), ('d', 'Waiting')], default='d', help_text='STATUS', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='status_ru',
            field=models.CharField(blank=True, choices=[('o', 'Available'), ('m', 'Refused'), ('d', 'Waiting')], default='d', help_text='STATUS', max_length=1, null=True),
        ),
    ]
