# Generated by Django 3.0.10 on 2021-04-01 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0035_auto_20210402_0125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='first_name_en',
        ),
        migrations.RemoveField(
            model_name='author',
            name='first_name_ru',
        ),
    ]
