# Generated by Django 3.0.10 on 2021-04-13 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0037_auto_20210405_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('pu', 'Public'), ('pr', 'Private')], default='pr', help_text='Book availability', max_length=5),
        ),
    ]
