# Generated by Django 3.0.10 on 2021-04-26 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0038_book_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='last_name_en',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_name_ru',
        ),
    ]
